In [1]:
import libspn as spn
import tensorflow as tf
import numpy as np
sess = tf.InteractiveSession()

# Generate SPN

In [2]:
gen = spn.TestSPNGenerator(spn_type = spn.TestSPNGenerator.Type.POON10_NAIVE_MIXTURE)
ivs, root = gen.generate()
spn.initialize_weights(root).run()

In [3]:
# spn.display_spn_graph(root)

# Value

In [4]:
value=root.get_value()
log_value=root.get_log_value()

In [5]:
value_array=value.eval(feed_dict={ivs: gen.feed})
value_array_log=np.exp(log_value.eval(feed_dict={ivs: gen.feed}))

print(value_array)
print(gen.true_values)
np.testing.assert_almost_equal(value_array, gen.true_values)
np.testing.assert_almost_equal(value_array_log, gen.true_values)

[[ 1.        ]
 [ 0.75      ]
 [ 0.25      ]
 [ 0.31      ]
 [ 0.228     ]
 [ 0.082     ]
 [ 0.69000006]
 [ 0.52200001]
 [ 0.16800001]]
[[ 1.        ]
 [ 0.75      ]
 [ 0.25      ]
 [ 0.31      ]
 [ 0.228     ]
 [ 0.082     ]
 [ 0.69      ]
 [ 0.52200001]
 [ 0.168     ]]


# MPE Value

In [6]:
mpe_value=root.get_value(spn.InferenceType.MPE)
log_mpe_value = root.get_log_value(spn.InferenceType.MPE)

In [7]:
mpe_value_array=mpe_value.eval(feed_dict={ivs: gen.feed})
mpe_value_array_log=np.exp(log_mpe_value.eval(feed_dict={ivs: gen.feed}))

print(mpe_value_array)
print(gen.true_values)
np.testing.assert_almost_equal(mpe_value_array, gen.true_mpe_values)
np.testing.assert_almost_equal(mpe_value_array_log, gen.true_mpe_values)

[[ 0.21600001]
 [ 0.21600001]
 [ 0.09      ]
 [ 0.14      ]
 [ 0.14      ]
 [ 0.06      ]
 [ 0.21600001]
 [ 0.21600001]
 [ 0.09      ]]
[[ 1.        ]
 [ 0.75      ]
 [ 0.25      ]
 [ 0.31      ]
 [ 0.228     ]
 [ 0.082     ]
 [ 0.69      ]
 [ 0.52200001]
 [ 0.168     ]]


# MPE Path

In [8]:
mpe_mpe_path_gen = spn.MPEPath(value_inference_type=spn.InferenceType.MPE, log=False)
mpe_mpe_path_gen.get_mpe_path(root)

In [9]:
print(mpe_mpe_path_gen.counts[ivs].eval(feed_dict={ivs: gen.feed}))

[[ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 1.  0.  1.  0.]
 [ 1.  0.  1.  0.]
 [ 1.  0.  0.  1.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  0.  1.]]


In [10]:
mpe_marginal_path_gen = spn.MPEPath(value_inference_type=spn.InferenceType.MARGINAL, log=False)
mpe_marginal_path_gen.get_mpe_path(root)

In [11]:
print(mpe_marginal_path_gen.counts[ivs].eval(feed_dict={ivs: gen.feed}))

[[ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 1.  0.  1.  0.]
 [ 1.  0.  1.  0.]
 [ 1.  0.  0.  1.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  0.  1.]]


# MPE State

In [12]:
mpe_state_gen = spn.MPEState(log=False)
ivs_state, = mpe_state_gen.get_state(root, ivs)

In [13]:
ivs_state.eval(feed_dict={ivs: [[-1, -1]]})

array([[1, 0]])