In [1]:
import tensorflow as tf
import libspn as spn
sess = tf.InteractiveSession()

# Create SPN

In [3]:
v=spn.IndicatorLeaf(num_vars=1, num_vals=4)
s=spn.Sum(v)
spn.generate_weights(s, tf.initializers.constant(3))

# Check Variable Collections

In [4]:
print(tf.all_variables())
print(tf.get_collection('spn_weights'))

Instructions for updating:
Please use tf.global_variables instead.


[WARNING] [tensorflow:warning] From <ipython-input-4-08d9e40a4ffe>:1: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.


[]
[<tf.Variable 'Weights_1/Sum_1_Weights/Variable:0' shape=(1, 4) dtype=float32_ref>]


# Initialize

In [5]:
spn.initialize_weights(s).run()
s.weights.node.get_value().eval()

array([[0.25, 0.25, 0.25, 0.25]], dtype=float32)

# Assign

In [11]:
shape = s.weights.node.variable.shape.as_list()
spn.assign_weights(s, tf.initializers.random_uniform(0,1)(shape=shape)).run()
print(s.weights.node.get_value().eval())

[[0.36888582 0.03072367 0.5680868  0.03230373]]


In [12]:
spn.assign_weights(s, tf.ones(shape)).run()
print(s.weights.node.get_value().eval())

[[0.25 0.25 0.25 0.25]]
