In [1]:
import tensorflow as tf
import libspn as spn
sess = tf.InteractiveSession()

# Create SPN

In [2]:
v=spn.IVs(num_vars=1, num_vals=4)
s=spn.Sum(v)
spn.generate_weights(s, 3)

# Check Variable Collections

In [3]:
print(tf.all_variables())
print(tf.get_collection('spn_weights'))

[]


# Initialize

In [4]:
spn.initialize_weights(s).run()
s.weights.node.get_value().eval()

array([ 0.25,  0.25,  0.25,  0.25], dtype=float32)

# Assign

In [5]:
spn.assign_weights(s, spn.ValueType.RANDOM_UNIFORM(0,1)).run()
print(s.weights.node.get_value().eval())

[ 0.10286223  0.39897418  0.21267007  0.28549349]


In [6]:
spn.assign_weights(s, 1).run()
print(s.weights.node.get_value().eval())

[ 0.25  0.25  0.25  0.25]
