In [1]:
import tensorflow as tf
import libspn as spn
import numpy as np
sess = tf.InteractiveSession()

In [2]:
a=[[1,2,3,4], [5,6,7,8], [9,10,11,12]]
b=[[13,14,15], [16,17,18], [19,20,21]]
c=np.eye(1000, 10)
print(c)

[[ 1.  0.  0. ...,  0.  0.  0.]
 [ 0.  1.  0. ...,  0.  0.  0.]
 [ 0.  0.  1. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]


In [3]:
p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)
i1 = tf.identity(p1)
i2 = tf.identity(p2)

In [4]:
i1.eval(feed_dict={p1:a, p2:b})

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.]], dtype=float32)

In [5]:
i2.eval(feed_dict={p1:a, p2:b})

array([[ 13.,  14.,  15.],
       [ 16.,  17.,  18.],
       [ 19.,  20.,  21.]], dtype=float32)

# Gather Columns

In [6]:
op = spn.utils.gather_cols(p1, [1,3])
sess.run(op, feed_dict={p1:a})

array([[  2.,   4.],
       [  6.,   8.],
       [ 10.,  12.]], dtype=float32)

In [7]:
op = tf.transpose(tf.gather_nd(tf.transpose(p1), tf.expand_dims([1, 3],1))) 
sess.run(op, feed_dict={p1:a})

array([[  2.,   4.],
       [  6.,   8.],
       [ 10.,  12.]], dtype=float32)

In [8]:
# ops = [spn.utils.gather_cols(p1, [1,3]) for i in range(10)]
# %timeit sess.run(ops, feed_dict={p1:c})

The slowest run took 121.74 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 529 µs per loop


In [9]:
# ops = [tf.transpose(tf.gather_nd(tf.transpose(p1), tf.expand_dims([1, 3],1))) for i in range(10)]
# %timeit sess.run(ops, feed_dict={p1:c})

The slowest run took 96.72 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 459 µs per loop
