In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [11]:
vals=[[0, 1, 2, -1],
      [0, 1, 2, -1]]
oh = tf.one_hot(vals, 3, dtype=tf.float32)
oh.eval()

array([[[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 0.,  0.,  0.]],

       [[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 0.,  0.,  0.]]], dtype=float32)

In [23]:
neg=tf.expand_dims(tf.cast(tf.less(vals, 0), dtype=tf.float32), dim=-1)
neg.eval()

array([[[ 0.],
        [ 0.],
        [ 0.],
        [ 1.]],

       [[ 0.],
        [ 0.],
        [ 0.],
        [ 1.]]], dtype=float32)

In [25]:
tf.add(oh, neg).eval()

array([[[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 1.,  1.,  1.]]], dtype=float32)