In [2]:
import tensorflow as tf
import libspn as spn
sess = tf.InteractiveSession()

# Product

In [4]:
counts = tf.placeholder(tf.float32, shape=(None, 1))

In [8]:
op=tf.tile(counts, [1, 3])

In [10]:
counts_feed = [[0], 
               [1],
               [2]]
op.eval(feed_dict={counts: counts_feed})

array([[ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 2.,  2.,  2.]], dtype=float32)

# Sum

In [18]:
values = tf.constant(np.random.uniform(size=(4,4)))
counts = tf.placeholder(tf.float32, shape=(None, 1))
print(values.eval())

[[ 0.13923439  0.12930088  0.1057721   0.41203472]
 [ 0.28917714  0.86338724  0.31982443  0.35560891]
 [ 0.78502111  0.57536015  0.47068129  0.86366622]
 [ 0.53368587  0.42820848  0.03110259  0.27815055]]


In [19]:
amax=tf.argmax(values, dimension=1)

In [20]:
values.get_shape().ndims

2

In [21]:
op = tf.one_hot(amax, values.get_shape()[1]) * counts

In [23]:
op.eval(feed_dict={counts:[[3], [1], [2], [4]]})

array([[ 0.,  0.,  0.,  3.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.],
       [ 4.,  0.,  0.,  0.]], dtype=float32)