In [16]:
num_sums=2
num_vals=3

In [6]:
i=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
i

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
latent_indicators = np.array([[0,1,0,1,0,1], [1,0,0,0,0,1], [0,1,0,1,0,1], [0,0,1,1,0,0]])
latent_indicators

array([[0, 1, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 0, 0]])

In [61]:
latent_indicatorsr=latent_indicators.reshape((-1, num_sums, num_vals))
latent_indicatorsr

array([[[0, 1, 0],
        [1, 0, 1]],

       [[1, 0, 0],
        [0, 0, 1]],

       [[0, 1, 0],
        [1, 0, 1]],

       [[0, 0, 1],
        [1, 0, 0]]])

In [10]:
w = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])
w

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6])

In [35]:
wr = w.reshape([num_sums, -1])
wr

array([[ 0.1,  0.2,  0.3],
       [ 0.4,  0.5,  0.6]])

In [62]:
print(i)
print(w)
print(wr)
print(latent_indicators)
print(latent_indicatorsr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 0.1  0.2  0.3  0.4  0.5  0.6]
[[ 0.1  0.2  0.3]
 [ 0.4  0.5  0.6]]
[[0 1 0 1 0 1]
 [1 0 0 0 0 1]
 [0 1 0 1 0 1]
 [0 0 1 1 0 0]]
[[[0 1 0]
  [1 0 1]]

 [[1 0 0]
  [0 0 1]]

 [[0 1 0]
  [1 0 1]]

 [[0 0 1]
  [1 0 0]]]


# Value (No IVs)

In [70]:
# Use the same idea for log values
np.sum(i.reshape([-1,1,i.shape[1]])*wr, axis=2)

array([[  1.4,   3.2],
       [  3.2,   7.7],
       [  5. ,  12.2],
       [  6.8,  16.7]])

In [47]:
np.tensordot(i, wr, axes=[1,1])

array([[  1.4,   3.2],
       [  3.2,   7.7],
       [  5. ,  12.2],
       [  6.8,  16.7]])

In [49]:
i@wr.transpose()

array([[  1.4,   3.2],
       [  3.2,   7.7],
       [  5. ,  12.2],
       [  6.8,  16.7]])

# Value (With IVs)

In [66]:
before_reduce = i.reshape([-1,1,i.shape[1]]) * (latent_indicatorsr*wr)
print(before_reduce)
np.sum(before_reduce, axis=2)

[[[ 0.   0.4  0. ]
  [ 0.4  0.   1.8]]

 [[ 0.4  0.   0. ]
  [ 0.   0.   3.6]]

 [[ 0.   1.6  0. ]
  [ 2.8  0.   5.4]]

 [[ 0.   0.   3.6]
  [ 4.   0.   0. ]]]


array([[ 0.4,  2.2],
       [ 0.4,  3.6],
       [ 1.6,  8.2],
       [ 3.6,  4. ]])

# Calculating MPE value (With IVs)

In [72]:
before_reduce = i.reshape([-1,1,i.shape[1]]) * (latent_indicatorsr*wr)
print(before_reduce)
np.amax(before_reduce, axis=2)

[[[ 0.   0.4  0. ]
  [ 0.4  0.   1.8]]

 [[ 0.4  0.   0. ]
  [ 0.   0.   3.6]]

 [[ 0.   1.6  0. ]
  [ 2.8  0.   5.4]]

 [[ 0.   0.   3.6]
  [ 4.   0.   0. ]]]


array([[ 0.4,  1.8],
       [ 0.4,  3.6],
       [ 1.6,  5.4],
       [ 3.6,  4. ]])