In [1]:
import tensorflow as tf
import libspn as spn
import numpy as np
sess = tf.InteractiveSession()

In [2]:
a=[[1,2,3,4], 
   [5,6,7,8], 
   [9,10,11,12]]
p1=tf.placeholder(tf.float32, shape=(None, 4))
c1=tf.constant(a)
ar1=np.array(a)

In [3]:
op = tf.concat(1, (tf.zeros( (tf.shape(p1)[0], 1) , dtype=tf.float32), p1) )
indices = np.array([3,1,7,8])
size = 10
gather_indices = np.zeros(size, dtype=np.int)
gather_indices[indices] = np.arange(indices.size)+1
op = spn.utils.gather_cols(op, gather_indices)
sess.run(op, feed_dict={p1:a})

array([[  0.,   2.,   0.,   1.,   0.,   0.,   0.,   3.,   4.,   0.],
       [  0.,   6.,   0.,   5.,   0.,   0.,   0.,   7.,   8.,   0.],
       [  0.,  10.,   0.,   9.,   0.,   0.,   0.,  11.,  12.,   0.]], dtype=float32)

In [4]:
b=[[1], 
   [5], 
   [9]]
p2=tf.placeholder(tf.float32, shape=(None, 1))

In [15]:
i=0
z=tf.concat(1, [tf.zeros((tf.shape(p2)[0], i), dtype=tf.float32), p2, 
               tf.zeros((tf.shape(p2)[0], size-i-1), dtype=tf.float32)])

In [16]:
z.eval(feed_dict={p2:b})

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [12]:
z[:, 3] = p2

TypeError: 'Tensor' object does not support item assignment

In [23]:
i=1
z=tf.pad(p2, [[0,0], [i,size-i-1]])

In [24]:
z.eval(feed_dict={p2:b})

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [26]:
tf.concat(concat_dim=0, values=[[0], [1]]).eval()

array([0, 1], dtype=int32)