In [1]:
tf

TensorFlow imported.
Interactive session created.


# Does assignment initialize?

In [2]:
v=tf.Variable(tf.zeros(3, dtype=tf.float64))

In [3]:
tf.report_uninitialized_variables().eval()

array([b'Variable'], dtype=object)

In [4]:
tf.assign(v, tf.zeros(3, dtype=tf.float64)).eval()

array([ 0.,  0.,  0.])

In [5]:
tf.report_uninitialized_variables().eval()


array([], dtype=object)

In [6]:
v.eval()

array([ 0.,  0.,  0.])

yes!!

# Is initialization only run once?

In [7]:
v=tf.Variable(tf.zeros(3, dtype=tf.float32))

In [8]:
v.initializer.run()

In [9]:
v.eval()

array([ 0.,  0.,  0.], dtype=float32)

In [10]:
tf.assign(v, tf.ones(3, dtype=tf.float32)).eval()

array([ 1.,  1.,  1.], dtype=float32)

In [11]:
v.eval()

array([ 1.,  1.,  1.], dtype=float32)

In [12]:
v.initializer.run()

In [13]:
v.eval()

array([ 0.,  0.,  0.], dtype=float32)

No!!

In [14]:
tf.all_variables()